import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header"

const inter = Inter({
  weight: ['100', '200', '300'],
  subsets: ["cyrillic"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <Header/>
        {children}</body>
    </html>
  );
}
